/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'Login': RouteRecordInfo<'Login', '/', Record<never, never>, Record<never, never>>,
    'ForgotPassword': RouteRecordInfo<'ForgotPassword', '/ForgotPassword', Record<never, never>, Record<never, never>>,
    'LoginV2': RouteRecordInfo<'LoginV2', '/loginV2', Record<never, never>, Record<never, never>>,
    'ResetPassword': RouteRecordInfo<'ResetPassword', '/ResetPassword/:token', Record<never, never>, Record<never, never>>,
    'VerifyEmail': RouteRecordInfo<'VerifyEmail', '/VerifyEmail', Record<never, never>, Record<never, never>>,
    'Company-Form': RouteRecordInfo<'Company-Form', 'company-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Company-List': RouteRecordInfo<'Company-List', '/Company/List', Record<never, never>, Record<never, never>>,
    'filing-new-components-count-all-data-invoices': RouteRecordInfo<'filing-new-components-count-all-data-invoices', '/Filing/New/Components/CountAllDataInvoices', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-contract': RouteRecordInfo<'filing-new-components-modal-contract', '/Filing/New/Components/ModalContract', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-errors': RouteRecordInfo<'filing-new-components-modal-errors', '/Filing/New/Components/ModalErrors', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-errors-filing': RouteRecordInfo<'filing-new-components-modal-errors-filing', '/Filing/New/Components/ModalErrorsFiling', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-errors-filing-invoice': RouteRecordInfo<'filing-new-components-modal-errors-filing-invoice', '/Filing/New/Components/ModalErrorsFilingInvoice', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-support-files': RouteRecordInfo<'filing-new-components-modal-support-files', '/Filing/New/Components/ModalSupportFiles', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-support-masive-files': RouteRecordInfo<'filing-new-components-modal-support-masive-files', '/Filing/New/Components/ModalSupportMasiveFiles', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-upload-file-json': RouteRecordInfo<'filing-new-components-modal-upload-file-json', '/Filing/New/Components/ModalUploadFileJson', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-upload-file-xml': RouteRecordInfo<'filing-new-components-modal-upload-file-xml', '/Filing/New/Components/ModalUploadFileXml', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-upload-file-zip': RouteRecordInfo<'filing-new-components-modal-upload-file-zip', '/Filing/New/Components/ModalUploadFileZip', Record<never, never>, Record<never, never>>,
    'filing-new-components-modal-xml-masive-files': RouteRecordInfo<'filing-new-components-modal-xml-masive-files', '/Filing/New/Components/ModalXmlMasiveFiles', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-emergencies': RouteRecordInfo<'filing-new-components-services-view-emergencies', '/Filing/New/Components/ServicesView/Emergencies', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-hospitalization': RouteRecordInfo<'filing-new-components-services-view-hospitalization', '/Filing/New/Components/ServicesView/Hospitalization', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-medicines': RouteRecordInfo<'filing-new-components-services-view-medicines', '/Filing/New/Components/ServicesView/Medicines', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-newly-born': RouteRecordInfo<'filing-new-components-services-view-newly-born', '/Filing/New/Components/ServicesView/NewlyBorn', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-other-services': RouteRecordInfo<'filing-new-components-services-view-other-services', '/Filing/New/Components/ServicesView/OtherServices', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-procedure': RouteRecordInfo<'filing-new-components-services-view-procedure', '/Filing/New/Components/ServicesView/Procedure', Record<never, never>, Record<never, never>>,
    'filing-new-components-services-view-queries': RouteRecordInfo<'filing-new-components-services-view-queries', '/Filing/New/Components/ServicesView/Queries', Record<never, never>, Record<never, never>>,
    'Filing-New-List': RouteRecordInfo<'Filing-New-List', 'Filing/New/List/:id', Record<never, never>, Record<never, never>>,
    'Filing-New-ListUsers': RouteRecordInfo<'Filing-New-ListUsers', 'Filing/New/ListUsers/:id/:invoice_id', Record<never, never>, Record<never, never>>,
    'Filing-New-ListUserServicesView': RouteRecordInfo<'Filing-New-ListUserServicesView', 'Filing/New/ListUserServicesView/:id/:numFactura/:numDocumentoIdentificacion', Record<never, never>, Record<never, never>>,
    'Filing-New-Index': RouteRecordInfo<'Filing-New-Index', '/Filing/New/Index', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'user-access-role-components-modal-form': RouteRecordInfo<'user-access-role-components-modal-form', '/UserAccess/Role/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'Role-List': RouteRecordInfo<'Role-List', '/UserAccess/Role/List', Record<never, never>, Record<never, never>>,
    'user-access-users-components-modal-form': RouteRecordInfo<'user-access-users-components-modal-form', '/UserAccess/Users/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'User-List': RouteRecordInfo<'User-List', '/UserAccess/Users/List', Record<never, never>, Record<never, never>>,
    'User-Profile': RouteRecordInfo<'User-Profile', '/UserAccess/Users/Profile', Record<never, never>, Record<never, never>>,
  }
}
